# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

group :test do
  gem 'byebug'
  gem 'minitest', require: 'minitest/autorun'
  gem 'rake'
end
